server:
  port: 8089
spring:
  application:
    name: Movie_review_21
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true
# ------------- DataBases
  datasource:
    url: jdbc:h2:./db/movie_review;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #        generate_statistics: true

  #  sql:
  #    init:
  #      mode: always

  liquibase:
    change-log: classpath:/db/changelog/master.yml

  output:
    ansi:
      enabled: always

  # ------------- Mail
  mail:
    host: smtp.gmail.com
    username: res.pswd.attractor@gmail.com
    password: udbj mooa cwid osgt
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            # ------------- Google
            #  security:
            #    oauth2:
            #      client:
            #        registration:
            #          google:
            #            client-id: [ client_id ]
            #            client-secret: [ client_secret ]
#            scope:
#              - email
#              - profile


logging:
  level:
    root: info
    org:
      springframework:
        security: debug
  #      hibernate:
  #        stat: debug
  file:
    path: logs
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger {36} - %msg%n"
