server:
  port: 8089
spring:
  application:
    name: Movie_review_21

# ------------- DataBases
  datasource:
    url: jdbc:h2:./db/movie_review;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always